### PR TITLE
Validation mode

### PR DESCRIPTION
**Pull request by olim7t**
Solves #8.

Additionally, we could improve the message in `logNumberOfFilesFormatted`, it's a bit ambiguous because we don't know if the files were modified or not. Suggestion: "Successfully _processed_ x files, formatted y". If you like the idea, I'll add a commit for that.

### CODE REVIEW

**Comment by malaporte** [comment]
Hmm I'm wondering, should we not prevent files from being written when this mode is activated? Right now, if you run the build twice, it'll pass the 2nd time, which is ... weird?

**Comment by olim7t** [comment]
@malaporte the primary use for this is the CI build, which should do a fresh checkout every time. On a developer's machine, I think it's slightly more convenient because you don't have to run another command after you found out the sources were not formatted (granted, user has to remember to git add the modified files, but there's not much we can do to check that apart from CI).
So I prefer modifying the files (but no strong feeling).

**Comment by olim7t** [comment]
Note -- there is also an open pull request on the formatter itself for validation mode: https://github.com/google/google-java-format/pull/106

**Comment by olim7t** [comment]
The more I think about it, the more it makes sense to not modify the files. It would be consistent with the formatter flag if that ever gets merged, and as for running another command it's easy enough to call `mvn fmt:format` and make the flag configurable. Also, fdecaa7 would not be needed anymore.
Anyways I've added it as another commit, tell me what you like best and I'll clean up the history.

**Comment by malaporte** [comment]
Oh indeed the code that copies the stuff is no longer needed, can you remove that part? Then I'll be able to merge and create a new release.

**Comment by olim7t** [comment]
Done, I've squashed everything into a single commit.

**Pull request merged**
