### PR TITLE
Add option to skip sorting imports. 

### PR DESCRIPTION
**Pull request by fraanek-pl**
Compatibility with --skip-sortintg-imports flag of google-java-format

### CODE REVIEW

**Comment by malaporte** [comment]
I'm curious to know why you need that particular switch?

**Comment by fraanek-pl** [comment]
We are using google-java-format plugin for IntelliJ, but the import ordering is not handled by this plugin.

**Comment by malaporte** [comment]
OK. Normally this plugin doesn't expose such options... but the IntelliJ issue is annoying enough to warrant one 😁

**Comment by fraanek-pl** [comment]
Thanks :+1:

**Pull request merged**
