### PR TITLE
Upgrade to google-java-format:1.1 + add file name filter

### PR DESCRIPTION
**Pull request by cprudhom**

### CODE REVIEW

**Comment by GuiSim** [comment]
Thanks for the PR!

Could you add a unit test for the `filterOnPattern` parameter?
Also, I think that a default value of `*.java` might be more appropriate. Thoughts?

**Comment by GuiSim** [comment]
I think that this will fix #3

**Comment by cprudhom** [comment]
I'll add a test.
I agree that the default value should be `*.java` but it requires to revamp the test suite since some assertions will be wrong. 
Do I modify the test suite too ?

**Comment by GuiSim** [comment]
Sounds good to me.
If it's simpler, you can modify the tests to use `.*` so you don't have to modify them too much.

**Comment by GuiSim** [comment]
You didn't have to modify the existing tests after all?

Very cool, thanks for the PR!
I sadly can't merge anymore but this has my approval 😄 

@malaporte could you please merge this?

**Comment by malaporte** [comment]
Looks good to me too, I'll merge and publish a new release soon.

**Pull request merged**
