### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cprudhom**
Move from 1.0.0 to 1.1.0

### CODE REVIEW

**Comment by cprudhom** [comment]
Maybe I made set the wrong version. I updated the README.md file with version 1.1.0, based on what I've seen [on the release menu](https://github.com/coveo/fmt-maven-plugin/releases).
But, [Maven Central Repository](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.coveo%22%20AND%20a%3A%22fmt-maven-plugin%22) already lists a release tagged 1.1.0 (19 Aug. 2016).
What is the correct version ? 

Additional question: did you automatically release on MCR too ?

**Comment by malaporte** [comment]
Yes but it typically takes a bit of time for a new version to become available (1-2 hours maybe). I did a deploy a few mins ago, but I now realize I forgot one very important flag (gets me each time), so I did another one. It should appear shortly.

**Comment by malaporte** [comment]
1.2.0 is now available in Maven Central.

**Comment by malaporte** [comment]
I somehow forgot to merge this, thanks!

**Pull request merged**
